### ISSUE TITLE
Add history

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid-desktop#18]
The up and down arrows keys could cycle through the history of messages. This would be really useful as when testing opsdroid you may want to send the same message repeatedly.

**Comment by Chandrasekar-G** [comment]
@jacobtomlinson Should we run opsdroid in our local. Is there any public end point I can point to instead?

**Comment by jacobtomlinson** [comment]
Hi. You will need to run opsdroid yourself locally. Thanks!

**Comment by sanjsanj** [comment]
Hey @jacobtomlinson I wanted to see if this was something I could do but having issues connecting locally.  I follow your instructions in the readme and the Opsdroid Desktop client does open up but it says it's disconnected and I can't send messages.

Is there any further setup I'm missing please?

**Comment by jacobtomlinson** [comment]
Fantastic!

Opsdroid desktop is for connecting to an opsdroid bot and chatting to it.
You need to get a bot up and running locally first, it’s quite straight
forward. See the website below for more info.

https://opsdroid.github.io

**Comment by sanjsanj** [comment]
I can install it fine but when I try and run it I get this error.

```
C:\dev\opsdroid-desktop>opsdroid
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\Scripts\opsdroid-script.py", line 11, in <module>
    load_entry_point('opsdroid==0.10.0', 'console_scripts', 'opsdroid')()
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\opsdroid\__main__.py", line 125, in main
    with OpsDroid() as opsdroid:
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\opsdroid\core.py", line 42, in __init__
    self.eventloop.add_signal_handler(sig, self.call_stop)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\asyncio\events.py", line 481, in add_signal_handler
    raise NotImplementedError
NotImplementedError
```

Apologies but I know next to nothing about python and I've had a look at the line that's erroring but that doesn't really mean anything to me.  Any advice on what the issue might be please?

**Comment by jacobtomlinson** [comment]
Ah! Looks like you've also hit opsdroid/opsdroid#353. Currently opsdroid does not support windows.

You'll either need to run it on a linux/maxOS machine, in a docker container or using a service like [ZEIT](https://medium.com/opsdroid/deploying-opsdroid-using-zeit-38296888a651).

Sorry!

**Comment by sanjsanj** [comment]
No worries, let me have a go with ZEIT when I get a chance and get back to you.

**Comment by sanjsanj** [comment]
Just to update you @jacobtomlinson I did have a go with ZEIT, I'm probably not far off but I couldn't manage to get it to work with the desktop client.  I won't have time for a while now so I'm going to bow out of this issue.  Thanks anyway and I'll be keeping an eye on further requests in the future.
