### ISSUE TITLE
Add message.room

### ISSUE THREAD

**Issue by dizzi90** [opsdroid/opsdroid-desktop#38]
version:
`v0.18.0`

`opsdroid start`

user:
> some_command_that_references_room

opsdroid-desktop:
> Check logs for details

logs:
> AttributeError: 'Message' object has no attribute 'room'

**Comment by jacobtomlinson** [comment]
`room` has been renamed to `target`. Where in opsdroid-desktop are you experiencing this?

**Comment by FabioRosado** [comment]
Hello @dizzi90 thank you for raising this PR, we have changed opsdroid a lot in the past year and unfortunately `opsdroid desktop` is running a bit behind. A few users told us that it could be good to split up opsdroid from the electron app and use only the web. 

Jacob has started that split on [opsdroid web](https://github.com/opsdroid/opsdroid-web).  We will be happy with a PR to fix this issue and update opsdroid desktop 😄

**Comment by dizzi90** [comment]
`__init__.py`
````python
from opsdroid.skill import Skill
from opsdroid.matchers import match_regex

class RoomSkill(Skill):
    @match_regex('room')
    def say_room(self, message):
        message.respond(f"{message.room}")

````
`configuration.yaml`
````yaml
welcome-message: false
connectors:
  websocket:
    botname: "bot"
skills:
  room:
    path: .
    no-cache: true
````
1. `opsdroid start`
2. Go to opsdroid-desktop

![image](https://user-images.githubusercontent.com/3081351/83978295-b7657900-a906-11ea-9f35-103379486b1f.png)

````
(skill-room) ➜  skill-room opsdroid start
INFO opsdroid.logging: ========================================
INFO opsdroid.logging: Started opsdroid v0.18.0.
WARNING opsdroid.loader: No databases in configuration. This will cause skills which store things in memory to lose data when opsdroid is restarted.
INFO opsdroid.web: Started web server on http://0.0.0.0:8080
INFO opsdroid.core: Opsdroid is now running, press ctrl+c to exit.
INFO aiohttp.access: 127.0.0.1 [07/Jun/2020:19:27:55 +0000] "POST /connector/websocket HTTP/1.1" 200 252 "-" "-"
ERROR opsdroid.core: Exception when running skill 'room'.
Traceback (most recent call last):
  File "/Users/dizzi90/.local/share/virtualenvs/skill-room-NbkEKT2L/lib/python3.7/site-packages/opsdroid/core.py", line 397, in run_skill
    return await skill(event)
  File "/Users/dizzi90/.local/share/virtualenvs/skill-room-NbkEKT2L/lib/python3.7/site-packages/opsdroid/skill/__init__.py", line 8, in decorated_skill
    return func(*args, **kwargs)
  File "/Users/dizzi90/Library/Application Support/opsdroid/opsdroid-modules/skill/room/__init__.py", line 7, in say_room
    message.respond(f"{message.room}")
AttributeError: 'Message' object has no attribute 'room'
````

**Comment by dizzi90** [comment]
got the same with shell actually

config:
````yaml
welcome-message: false
logging:
  path: "room.log"
  console: false
connectors:
  shell:
    botname: "bot"
skills:
  room:
    path: .
    no-cache: true


````

````shell
(skill-room) ➜  skill-room opsdroid start
opsdroid> room
Whoops there has been an error.
Check the log for details.
````


log:
````log
INFO opsdroid.logging: ========================================
INFO opsdroid.logging: Started opsdroid v0.18.0.
WARNING opsdroid.loader: No databases in configuration. This will cause skills which store things in memory to lose data when opsdroid is restarted.
INFO opsdroid.web: Started web server on http://0.0.0.0:8080
INFO opsdroid.core: Opsdroid is now running, press ctrl+c to exit.
ERROR opsdroid.core: Exception when running skill 'room'.
Traceback (most recent call last):
  File "/Users/dizzi90/.local/share/virtualenvs/skill-room-NbkEKT2L/lib/python3.7/site-packages/opsdroid/core.py", line 397, in run_skill
    return await skill(event)
  File "/Users/dizzi90/.local/share/virtualenvs/skill-room-NbkEKT2L/lib/python3.7/site-packages/opsdroid/skill/__init__.py", line 8, in decorated_skill
    return func(*args, **kwargs)
  File "/Users/dizzi90/Library/Application Support/opsdroid/opsdroid-modules/skill/room/__init__.py", line 7, in say_room
    message.respond(f"{message.room}")
AttributeError: 'Message' object has no attribute 'room'
INFO opsdroid.core: Received stop signal, exiting.
INFO opsdroid.core: Removing skills...
INFO opsdroid.core: Removed room.
INFO opsdroid.core: Stopping connector shell...
INFO opsdroid.core: Stopped connector shell.
INFO opsdroid.core: Stopping database ...
INFO opsdroid.core: Stopped database .
INFO opsdroid.core: Stopping web server...
INFO opsdroid.core: Stopped web server.
INFO opsdroid.core: Stopping cron...
INFO opsdroid.core: Stopped cron
INFO opsdroid.core: Stopping pending tasks...
INFO opsdroid.core: Stopped pending tasks.
INFO opsdroid.core: Bye!
INFO opsdroid.core: Exiting application with return code 0.

````
